/*
 * TrashNet 6-Class Classifier for ESP32-S3 + OV2640
 * ===================================================
 * trash_model_data.h  –  Declares the byte array that holds the
 * flat-buffer TFLite model embedded directly in flash.
 *
 * The actual array is generated by running:
 *   xxd -i trash_model_int8.tflite > trash_model_data.cc
 *
 * Then rename the generated symbol to  g_trash_model_data  and
 * g_trash_model_data_len  (see trash_model_data.cc for details).
 */

#pragma once

#include <cstdint>

// Pointer to model data array stored in flash (DROM / rodata)
extern const unsigned char g_trash_model_data[];

// Total byte length of the array
extern const unsigned int  g_trash_model_data_len;
