#!/usr/bin/env bash
# =============================================================================
# generate_model_cc.sh  –  Convert TFLite model binary → C array for embedding
# =============================================================================
# Usage:
#   chmod +x generate_model_cc.sh
#   ./generate_model_cc.sh trash_model_int8.tflite
#
# Output: trash_classifier/main/trash_model_data.cc
# =============================================================================

set -e

INPUT="${1:-trash_model_int8.tflite}"
OUTPUT="../main/trash_model_data.cc"

if [ ! -f "$INPUT" ]; then
    echo "ERROR: Input file not found: $INPUT"
    echo "Usage: $0 <model.tflite>"
    exit 1
fi

echo "Converting $INPUT → $OUTPUT ..."

# Step 1: Generate raw xxd output
TMP_FILE=$(mktemp /tmp/model_data_XXXXXX.cc)
xxd -i "$INPUT" > "$TMP_FILE"

# Step 2: Extract raw array name (e.g. "trash_model_int8_tflite")
RAW_ARRAY=$(grep 'unsigned char ' "$TMP_FILE" | sed 's/unsigned char \([^ ]*\)\[\].*/\1/')
RAW_LEN=$(grep 'unsigned int ' "$TMP_FILE" | sed 's/unsigned int \([^ ]*\).*/\1/')

echo "  Raw array name: $RAW_ARRAY"
echo "  Raw length var: $RAW_LEN"

# Step 3: Write the final .cc file with proper names
cat > "$OUTPUT" << HEADER
/*
 * trash_model_data.cc  –  AUTO-GENERATED by generate_model_cc.sh
 * ================================================================
 * Generated from: $INPUT
 * Generated on  : $(date)
 *
 * Do NOT edit manually.  To regenerate:
 *   ./generate_model_cc.sh $INPUT
 */

#include "trash_model_data.h"

// Model data array (stored in DROM / read-only flash)
const unsigned char g_trash_model_data[] = {
HEADER

# Step 4: Extract just the hex bytes (skip the "unsigned char name[] = {" line)
grep -v 'unsigned char\|unsigned int\|^};' "$TMP_FILE" >> "$OUTPUT"

# Close the array
echo "};" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Step 5: Append the length
RAW_LEN_VAL=$(grep 'unsigned int ' "$TMP_FILE" | sed 's/.*= \([0-9]*\);/\1/')
echo "const unsigned int g_trash_model_data_len = ${RAW_LEN_VAL};" >> "$OUTPUT"

# Cleanup
rm -f "$TMP_FILE"

echo ""
echo "✓ Done! Written to: $OUTPUT"
echo ""
echo "File size check:"
wc -c "$INPUT"
echo ""
echo "Next: idf.py -p /dev/ttyUSB0 flash monitor"
